# Import Dependencies

In [44]:
import pandas as pd

# Load Data

In [46]:
data = pd.read_csv("doraemon_movies.csv")

In [47]:
data = data.loc[:,"Movie":]

In [48]:
data.head()

,Movie,Date
0,Doraemon: Nobita's Dinosaur,"Japanese\nMarch 15, 1980\nAugust 14, 1982\nTha..."
1,"Doraemon: The Records of Nobita, Spaceblazer","Japanese\nMarch 14, 1981\nThai\nOctober 1, 198..."
2,Doraemon: Nobita and the Haunts of Evil,"Japanese\nMarch 13, 1982\nItalian\nMarch 10, 1985"
3,Doraemon: Nobita and the Castle of the Underse...,"Japanese\nMarch 12, 1983\nSpanish\nMarch 2, 20..."
4,Doraemon: Nobita's Great Adventure into the Un...,"Japanese\nMarch 17, 1984"

# Mengecek Nama Negara dan Tanggal Rilis

In [50]:
isCountry = False
countryDate = []
ultiCountryDate = []
country = []
# statebreak=False
for iMovie in range(len(data)):
    countryDate = []
    date = data.loc[iMovie,"Date"].split("\n")
    # Mendapatkan semua element (Date dan Country)
    for element in date:
        # apabila element memiliki digit maka Country
        if (any(char.isdigit() for char in element))==False and isCountry==False:
            isCountry=True
            countryDate.append(element)
            country.append(element)
        # apabila element tidak memiliki digit maka bukan Country
        elif (any(char.isdigit() for char in element))==True and isCountry==True:
            isCountry=False
            countryDate.append(element)
        else:
            continue
    #     if element=="":
    #         statebreak=True
    # if statebreak==True:
    #     break
    ultiCountryDate.append(countryDate)
country=set(country) #mendapatkan semua country yang tersedia

In [51]:
country=pd.DataFrame(columns=list(country)[1:],index=[0]) # membersihkan data country

In [52]:
# merapikan menjadi dataframe
for idata in range(len(data)):
    for ielement in range(len(ultiCountryDate[idata])):
        if any(char.isdigit() for char in ultiCountryDate[idata][ielement])==False:
            Country = ultiCountryDate[idata][ielement]
            Date = ultiCountryDate[idata][ielement+1]
            country.loc[idata,Country]=Date

In [53]:
country.head()

,Spanish,Chinese,Viatnamese,Indonesian,Filipino,English,Thai,Japanese,Italian,
0,NaN,NaN,NaN,NaN,NaN,NaN,"August 21, 1982","March 15, 1980","March 3, 1985",NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,"October 1, 1982","March 14, 1981","March 17, 1985",NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"March 13, 1982","March 10, 1985",NaN
3,"March 2, 2011",NaN,NaN,NaN,NaN,NaN,NaN,"March 12, 1983",NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"March 17, 1984",NaN,NaN

In [54]:
ulti = pd.concat([data,country],axis=1)

In [55]:
ulti.drop(["Date",""],axis=1,inplace=True)

In [56]:
ulti.head()

,Movie,Spanish,Chinese,Viatnamese,Indonesian,Filipino,English,Thai,Japanese,Italian
0,Doraemon: Nobita's Dinosaur,NaN,NaN,NaN,NaN,NaN,NaN,"August 21, 1982","March 15, 1980","March 3, 1985"
1,"Doraemon: The Records of Nobita, Spaceblazer",NaN,NaN,NaN,NaN,NaN,NaN,"October 1, 1982","March 14, 1981","March 17, 1985"
2,Doraemon: Nobita and the Haunts of Evil,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"March 13, 1982","March 10, 1985"
3,Doraemon: Nobita and the Castle of the Underse...,"March 2, 2011",NaN,NaN,NaN,NaN,NaN,NaN,"March 12, 1983",NaN
4,Doraemon: Nobita's Great Adventure into the Un...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"March 17, 1984",NaN

# Cek Absahan

In [58]:
data.head()

,Movie,Date
0,Doraemon: Nobita's Dinosaur,"Japanese\nMarch 15, 1980\nAugust 14, 1982\nTha..."
1,"Doraemon: The Records of Nobita, Spaceblazer","Japanese\nMarch 14, 1981\nThai\nOctober 1, 198..."
2,Doraemon: Nobita and the Haunts of Evil,"Japanese\nMarch 13, 1982\nItalian\nMarch 10, 1985"
3,Doraemon: Nobita and the Castle of the Underse...,"Japanese\nMarch 12, 1983\nSpanish\nMarch 2, 20..."
4,Doraemon: Nobita's Great Adventure into the Un...,"Japanese\nMarch 17, 1984"

In [59]:
ulti

,Movie,Spanish,Chinese,Viatnamese,Indonesian,Filipino,English,Thai,Japanese,Italian
0,Doraemon: Nobita's Dinosaur,NaN,NaN,NaN,NaN,NaN,NaN,"August 21, 1982","March 15, 1980","March 3, 1985"
1,"Doraemon: The Records of Nobita, Spaceblazer",NaN,NaN,NaN,NaN,NaN,NaN,"October 1, 1982","March 14, 1981","March 17, 1985"
2,Doraemon: Nobita and the Haunts of Evil,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"March 13, 1982","March 10, 1985"
3,Doraemon: Nobita and the Castle of the Underse...,"March 2, 2011",NaN,NaN,NaN,NaN,NaN,NaN,"March 12, 1983",NaN
4,Doraemon: Nobita's Great Adventure into the Un...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"March 17, 1984",NaN
5,Doraemon: Nobita's Little Star Wars,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"March 16, 1985",NaN
6,Doraemon: Nobita and the Steel Troops,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"March 15, 1986",NaN
7,Doraemon: Nobita and the Knights on Dinosaurs,"April 25, 2007",NaN,NaN,NaN,NaN,NaN,NaN,"March 14, 1987",NaN
8,Doraemon: The Record of Nobita's Parallel Visi...,"November 20, 2012",NaN,NaN,NaN,NaN,NaN,NaN,"March 12, 1988",NaN
9,Doraemon: Nobita and the Birth of Japan,"April 7, 1996",NaN,NaN,NaN,NaN,NaN,"March 11, 2005","March 11, 1989",NaN
10,Doraemon: Nobita and the Animal Planet,NaN,NaN,"December 7, 2012",NaN,NaN,NaN,NaN,"March 10, 1990",NaN
11,Doraemon: Nobita's Dorabian Nights,"June 15, 2001",NaN,NaN,NaN,NaN,NaN,NaN,"March 9, 1991","December 24, 2004"
12,Doraemon: Nobita and the Kingdom of Clouds,"October 20, 2004",NaN,NaN,NaN,NaN,NaN,NaN,"March 7, 1992",NaN
13,Doraemon: Nobita and the Tin Labyrinth,"February 24, 2002",NaN,NaN,NaN,NaN,NaN,NaN,"March 6, 1993",NaN
14,Doraemon: Nobita's Three Visionary Swordsmen,NaN,"August 31, 2011 (CCTV-6)","June 28, 2013",NaN,NaN,NaN,NaN,"March 12, 1994",NaN
15,Doraemon: Nobita's Diary on the Creation of th...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"March 4, 1995",NaN
16,Doraemon: Nobita and the Galaxy Super-express,"October 14, 2003",NaN,NaN,NaN,NaN,NaN,NaN,"March 2, 1996",NaN
17,Doraemon: Nobita and the Spiral City,"October 25, 2005 (DVD)",NaN,NaN,NaN,NaN,NaN,NaN,"March 8, 1997",NaN
18,Doraemon: Nobita's Great Adventure in the Sout...,"August 30, 2002",NaN,NaN,NaN,NaN,NaN,NaN,"March 7, 1998",NaN
19,Doraemon: Nobita Drifts in the Universe,"June 3, 2009",NaN,NaN,NaN,NaN,NaN,NaN,"March 6th, 1999",NaN
20,Doraemon: Nobita's Legend of the Sun King,"August 29, 2003",NaN,"March 1, 2013",NaN,NaN,NaN,"October 11, 2002","March 11, 2000",NaN
21,Doraemon: Nobita and the Winged Braves,"October 25, 2006",NaN,NaN,NaN,NaN,NaN,"October 11, 2003","March 10, 2001",NaN
22,Doraemon: Nobita in the Robot Kingdom,"August 27, 2004",NaN,NaN,NaN,NaN,NaN,"September 30, 2004","March 9, 2002",NaN
23,Doraemon: Nobita and the Windmasters,"September 9, 2005",NaN,NaN,NaN,NaN,NaN,"October 13, 2005","March 8, 2003",NaN
24,Doraemon: Nobita in the Wan-Nyan Spacetime Ody...,NaN,NaN,"March 29, 2013",NaN,NaN,NaN,"October 19, 2006","March 6, 2004",NaN
25,Doraemon: Nobita's Dinosaur 2006,"August 31, 2007","July 21, 2007",NaN,"April 29, 2014 (DVD)",NaN,NaN,"October 11, 2007","March 4, 2006","December 24, 2013"
26,Doraemon: Nobita's New Great Adventure into th...,"November 26, 2008","January 22, 2008","September 20, 2013",NaN,NaN,NaN,"October 23, 2008","March 10, 2007",NaN
27,Doraemon: Nobita and the Green Giant Legend,"November 11, 2009","August 4, 2009","September 27, 2013","May 6, 2017",NaN,NaN,"October 29, 2009","March 8, 2008",NaN
28,Doraemon: The Record of Nobita's Spaceblazer,"November 3, 2010","May 2, 2013 (DVD)",NaN,"July 26, 2010",NaN,NaN,NaN,"March 7, 2009",NaN
29,Doraemon: Nobita's Great Battle of the Mermaid...,NaN,"December 9, 2010","June 7, 2013",NaN,NaN,NaN,"October 14, 2010","March 6, 2010",NaN
30,Doraemon: Nobita and the New Steel Troops ~Win...,"April 16, 2013","April 5, 2013(DVD)",NaN,NaN,NaN,NaN,"October 6, 2011","March 5, 2011",NaN
31,Doraemon: Nobita and the Island of Miracles ~A...,"June 22, 2015 (direct download)","April 5, 2013",NaN,NaN,"November 28, 2015 (part 1) November 29, 2015 (...",NaN,"October 18, 2012","March 3, 2012",NaN
32,Doraemon: Nobita's Secret Gadget Museum,"October 31, 2013",NaN,"December 27, 2013",NaN,NaN,NaN,"October 17, 2013","March 9, 2013",NaN
33,Doraemon: New Nobita's Great Demon ~Peko and t...,"May 31, 2017","June 14, 2014 (Shanghai International Film Fes...","July 4, 2014",NaN,NaN,NaN,NaN,"March 8, 2014",NaN
34,Stand by Me Doraemon,"December 19, 2014","May 28, 2015","December 12, 2014","December 18, 2014","June 17, 2015","December 24, 2021","December 31, 2014","August 8, 2014","November 6, 2014"
35,Doraemon: Nobita's Space Heroes,"March 9, 2015",NaN,"June 26, 2015","July 22, 2015","August 5, 2015",NaN,"May 4, 2017","March 7, 2015","January 28, 2016"
36,Doraemon: Nobita and the Birth of Japan 2016,NaN,NaN,"May 27, 2016","February 24, 2017",NaN,NaN,"February 16, 2017","March 5, 2016",NaN
37,Doraemon: Nobita's Great Adventure in the Anta...,"November 2, 2018",NaN,"May 26, 2017",NaN,NaN,NaN,"March 29, 2018","March 4, 2017","July 5, 2018"
38,Doraemon: Nobita's Treasure Island,"November 15, 2019","June 1, 2018","May 25, 2018",NaN,NaN,"April 3, 2018 (DVD)","October 18, 2018","March 3, 2018","September 24, 2020"
39,Doraemon: Nobita's Chronicle of the Moon Explo...,NaN,"June 1, 2019","May 24, 2019","March 25, 2020)","July 24, 2019",NaN,"October 3, 2019","March 1, 2019",NaN
40,Doraemon: Nobita's New Dinosaur,"October 20, 2023","December 11, 2020","December 18, 2020","March 10, 2021[4]","February 19, 2021[2]",NaN,"November 19, 2020","August 7, 2020[1]",NaN
41,Stand by Me Doraemon 2,"December 22, 2021","May 28, 2021","December 17, 2021","February 19, 2021 | February 25 (IMAX)","February 24, 2021 (JP Dub, EN Sub)",NaN,"April 1-5, 2021 (Special preview) | April 6, 2021","November 20, 2020","September 11, 2021 (Boomerang PPV, IT Dub)"
42,Doraemon: Nobita's Little Space Wars 2021,NaN,"May 28, 2022","May 27, 2022","May 25, 2022","July 9, 2022",NaN,"October 6, 2022","March 4, 2022",NaN
43,Doraemon: Nobita's Sky Utopia,NaN,"June 1, 2023","May 25, 2023","July 19, 2023","August 2, 2023",NaN,"October 5, 2023","March 3, 2023",NaN